// AUTO-GENERATED by scripts/gen-styles.mjs from
// crates/ui-components/src/virtual_tree/style_table.json and color_tokens.json.
// Do not edit by hand: run `node scripts/gen-styles.mjs`.

export type ThemeColorToken = "background" | "foreground" | "surface" | "surface_foreground" | "primary" | "primary_foreground" | "primary_hover" | "primary_active" | "secondary" | "secondary_foreground" | "muted" | "muted_foreground" | "accent" | "accent_foreground" | "danger" | "danger_foreground" | "success" | "success_foreground" | "info" | "info_foreground" | "border" | "input" | "ring" | "popover" | "popover_foreground" | "list" | "list_hover" | "list_active" | "link" | "selection" | "caret" | "scrollbar" | "scrollbar_thumb" | "skeleton" | "title_bar" | "tab" | "tab_active" | "tab_foreground" | "table" | "table_head" | "table_head_foreground" | "table_row_border";

export type ColorInput = ThemeColorToken | `#${string}`;

export type LengthInput = number | `${number}px` | `${number}%`;

export type AbsoluteInput = number | `${number}px`;

export type FontWeightName = "thin" | "extra_light" | "light" | "normal" | "medium" | "semibold" | "bold" | "extra_bold" | "black";

/**
 * Base class of every element builder. Each method here is one entry of the
 * host's canonical style table, so the two cannot drift.
 */
export class StyledElement {
  protected _style: Record<string, unknown> = {};

  /** Escape hatch for a style method added to the table after an SDK release. */
  style(name: string, value: unknown): this {
    this._style[name] = value;
    return this;
  }

  flex(): this {
    this._style["flex"] = true;
    return this;
  }

  flex_1(): this {
    this._style["flex_1"] = true;
    return this;
  }

  flex_auto(): this {
    this._style["flex_auto"] = true;
    return this;
  }

  flex_none(): this {
    this._style["flex_none"] = true;
    return this;
  }

  flex_col(): this {
    this._style["flex_col"] = true;
    return this;
  }

  flex_row(): this {
    this._style["flex_row"] = true;
    return this;
  }

  flex_col_reverse(): this {
    this._style["flex_col_reverse"] = true;
    return this;
  }

  flex_row_reverse(): this {
    this._style["flex_row_reverse"] = true;
    return this;
  }

  flex_wrap(): this {
    this._style["flex_wrap"] = true;
    return this;
  }

  flex_wrap_reverse(): this {
    this._style["flex_wrap_reverse"] = true;
    return this;
  }

  flex_nowrap(): this {
    this._style["flex_nowrap"] = true;
    return this;
  }

  flex_grow_0(): this {
    this._style["flex_grow_0"] = true;
    return this;
  }

  flex_grow_1(): this {
    this._style["flex_grow_1"] = true;
    return this;
  }

  flex_shrink_0(): this {
    this._style["flex_shrink_0"] = true;
    return this;
  }

  flex_shrink_1(): this {
    this._style["flex_shrink_1"] = true;
    return this;
  }

  items_start(): this {
    this._style["items_start"] = true;
    return this;
  }

  items_center(): this {
    this._style["items_center"] = true;
    return this;
  }

  items_end(): this {
    this._style["items_end"] = true;
    return this;
  }

  items_baseline(): this {
    this._style["items_baseline"] = true;
    return this;
  }

  items_stretch(): this {
    this._style["items_stretch"] = true;
    return this;
  }

  justify_start(): this {
    this._style["justify_start"] = true;
    return this;
  }

  justify_center(): this {
    this._style["justify_center"] = true;
    return this;
  }

  justify_end(): this {
    this._style["justify_end"] = true;
    return this;
  }

  justify_between(): this {
    this._style["justify_between"] = true;
    return this;
  }

  justify_around(): this {
    this._style["justify_around"] = true;
    return this;
  }

  justify_evenly(): this {
    this._style["justify_evenly"] = true;
    return this;
  }

  self_start(): this {
    this._style["self_start"] = true;
    return this;
  }

  self_center(): this {
    this._style["self_center"] = true;
    return this;
  }

  self_end(): this {
    this._style["self_end"] = true;
    return this;
  }

  self_stretch(): this {
    this._style["self_stretch"] = true;
    return this;
  }

  self_baseline(): this {
    this._style["self_baseline"] = true;
    return this;
  }

  relative(): this {
    this._style["relative"] = true;
    return this;
  }

  absolute(): this {
    this._style["absolute"] = true;
    return this;
  }

  hidden(): this {
    this._style["hidden"] = true;
    return this;
  }

  block(): this {
    this._style["block"] = true;
    return this;
  }

  visible(): this {
    this._style["visible"] = true;
    return this;
  }

  invisible(): this {
    this._style["invisible"] = true;
    return this;
  }

  overflow_hidden(): this {
    this._style["overflow_hidden"] = true;
    return this;
  }

  overflow_x_hidden(): this {
    this._style["overflow_x_hidden"] = true;
    return this;
  }

  overflow_y_hidden(): this {
    this._style["overflow_y_hidden"] = true;
    return this;
  }

  size_full(): this {
    this._style["size_full"] = true;
    return this;
  }

  w_full(): this {
    this._style["w_full"] = true;
    return this;
  }

  h_full(): this {
    this._style["h_full"] = true;
    return this;
  }

  w_auto(): this {
    this._style["w_auto"] = true;
    return this;
  }

  h_auto(): this {
    this._style["h_auto"] = true;
    return this;
  }

  size_auto(): this {
    this._style["size_auto"] = true;
    return this;
  }

  aspect_square(): this {
    this._style["aspect_square"] = true;
    return this;
  }

  rounded_none(): this {
    this._style["rounded_none"] = true;
    return this;
  }

  rounded_xs(): this {
    this._style["rounded_xs"] = true;
    return this;
  }

  rounded_sm(): this {
    this._style["rounded_sm"] = true;
    return this;
  }

  rounded_md(): this {
    this._style["rounded_md"] = true;
    return this;
  }

  rounded_lg(): this {
    this._style["rounded_lg"] = true;
    return this;
  }

  rounded_xl(): this {
    this._style["rounded_xl"] = true;
    return this;
  }

  rounded_full(): this {
    this._style["rounded_full"] = true;
    return this;
  }

  text_xs(): this {
    this._style["text_xs"] = true;
    return this;
  }

  text_sm(): this {
    this._style["text_sm"] = true;
    return this;
  }

  text_base(): this {
    this._style["text_base"] = true;
    return this;
  }

  text_lg(): this {
    this._style["text_lg"] = true;
    return this;
  }

  text_xl(): this {
    this._style["text_xl"] = true;
    return this;
  }

  text_2xl(): this {
    this._style["text_2xl"] = true;
    return this;
  }

  text_3xl(): this {
    this._style["text_3xl"] = true;
    return this;
  }

  text_left(): this {
    this._style["text_left"] = true;
    return this;
  }

  text_center(): this {
    this._style["text_center"] = true;
    return this;
  }

  text_right(): this {
    this._style["text_right"] = true;
    return this;
  }

  truncate(): this {
    this._style["truncate"] = true;
    return this;
  }

  text_ellipsis(): this {
    this._style["text_ellipsis"] = true;
    return this;
  }

  italic(): this {
    this._style["italic"] = true;
    return this;
  }

  not_italic(): this {
    this._style["not_italic"] = true;
    return this;
  }

  underline(): this {
    this._style["underline"] = true;
    return this;
  }

  line_through(): this {
    this._style["line_through"] = true;
    return this;
  }

  whitespace_nowrap(): this {
    this._style["whitespace_nowrap"] = true;
    return this;
  }

  whitespace_normal(): this {
    this._style["whitespace_normal"] = true;
    return this;
  }

  cursor_pointer(): this {
    this._style["cursor_pointer"] = true;
    return this;
  }

  cursor_text(): this {
    this._style["cursor_text"] = true;
    return this;
  }

  cursor_default(): this {
    this._style["cursor_default"] = true;
    return this;
  }

  w(value: LengthInput): this {
    this._style["w"] = value;
    return this;
  }

  h(value: LengthInput): this {
    this._style["h"] = value;
    return this;
  }

  size(value: LengthInput): this {
    this._style["size"] = value;
    return this;
  }

  min_w(value: LengthInput): this {
    this._style["min_w"] = value;
    return this;
  }

  min_h(value: LengthInput): this {
    this._style["min_h"] = value;
    return this;
  }

  min_size(value: LengthInput): this {
    this._style["min_size"] = value;
    return this;
  }

  max_w(value: LengthInput): this {
    this._style["max_w"] = value;
    return this;
  }

  max_h(value: LengthInput): this {
    this._style["max_h"] = value;
    return this;
  }

  max_size(value: LengthInput): this {
    this._style["max_size"] = value;
    return this;
  }

  m(value: LengthInput): this {
    this._style["m"] = value;
    return this;
  }

  mx(value: LengthInput): this {
    this._style["mx"] = value;
    return this;
  }

  my(value: LengthInput): this {
    this._style["my"] = value;
    return this;
  }

  mt(value: LengthInput): this {
    this._style["mt"] = value;
    return this;
  }

  mb(value: LengthInput): this {
    this._style["mb"] = value;
    return this;
  }

  ml(value: LengthInput): this {
    this._style["ml"] = value;
    return this;
  }

  mr(value: LengthInput): this {
    this._style["mr"] = value;
    return this;
  }

  p(value: LengthInput): this {
    this._style["p"] = value;
    return this;
  }

  px(value: LengthInput): this {
    this._style["px"] = value;
    return this;
  }

  py(value: LengthInput): this {
    this._style["py"] = value;
    return this;
  }

  pt(value: LengthInput): this {
    this._style["pt"] = value;
    return this;
  }

  pb(value: LengthInput): this {
    this._style["pb"] = value;
    return this;
  }

  pl(value: LengthInput): this {
    this._style["pl"] = value;
    return this;
  }

  pr(value: LengthInput): this {
    this._style["pr"] = value;
    return this;
  }

  inset(value: LengthInput): this {
    this._style["inset"] = value;
    return this;
  }

  top(value: LengthInput): this {
    this._style["top"] = value;
    return this;
  }

  bottom(value: LengthInput): this {
    this._style["bottom"] = value;
    return this;
  }

  left(value: LengthInput): this {
    this._style["left"] = value;
    return this;
  }

  right(value: LengthInput): this {
    this._style["right"] = value;
    return this;
  }

  gap(value: LengthInput): this {
    this._style["gap"] = value;
    return this;
  }

  gap_x(value: LengthInput): this {
    this._style["gap_x"] = value;
    return this;
  }

  gap_y(value: LengthInput): this {
    this._style["gap_y"] = value;
    return this;
  }

  flex_basis(value: LengthInput): this {
    this._style["flex_basis"] = value;
    return this;
  }

  line_height(value: LengthInput): this {
    this._style["line_height"] = value;
    return this;
  }

  border(value: AbsoluteInput): this {
    this._style["border"] = value;
    return this;
  }

  border_t(value: AbsoluteInput): this {
    this._style["border_t"] = value;
    return this;
  }

  border_b(value: AbsoluteInput): this {
    this._style["border_b"] = value;
    return this;
  }

  border_l(value: AbsoluteInput): this {
    this._style["border_l"] = value;
    return this;
  }

  border_r(value: AbsoluteInput): this {
    this._style["border_r"] = value;
    return this;
  }

  border_x(value: AbsoluteInput): this {
    this._style["border_x"] = value;
    return this;
  }

  border_y(value: AbsoluteInput): this {
    this._style["border_y"] = value;
    return this;
  }

  rounded(value: AbsoluteInput): this {
    this._style["rounded"] = value;
    return this;
  }

  rounded_t(value: AbsoluteInput): this {
    this._style["rounded_t"] = value;
    return this;
  }

  rounded_b(value: AbsoluteInput): this {
    this._style["rounded_b"] = value;
    return this;
  }

  rounded_l(value: AbsoluteInput): this {
    this._style["rounded_l"] = value;
    return this;
  }

  rounded_r(value: AbsoluteInput): this {
    this._style["rounded_r"] = value;
    return this;
  }

  rounded_tl(value: AbsoluteInput): this {
    this._style["rounded_tl"] = value;
    return this;
  }

  rounded_tr(value: AbsoluteInput): this {
    this._style["rounded_tr"] = value;
    return this;
  }

  rounded_bl(value: AbsoluteInput): this {
    this._style["rounded_bl"] = value;
    return this;
  }

  rounded_br(value: AbsoluteInput): this {
    this._style["rounded_br"] = value;
    return this;
  }

  text_size(value: AbsoluteInput): this {
    this._style["text_size"] = value;
    return this;
  }

  opacity(value: number): this {
    this._style["opacity"] = value;
    return this;
  }

  flex_grow(value: number): this {
    this._style["flex_grow"] = value;
    return this;
  }

  flex_shrink(value: number): this {
    this._style["flex_shrink"] = value;
    return this;
  }

  aspect_ratio(value: number): this {
    this._style["aspect_ratio"] = value;
    return this;
  }

  line_clamp(value: number): this {
    this._style["line_clamp"] = value;
    return this;
  }

  bg(value: ColorInput): this {
    this._style["bg"] = value;
    return this;
  }

  text_color(value: ColorInput): this {
    this._style["text_color"] = value;
    return this;
  }

  border_color(value: ColorInput): this {
    this._style["border_color"] = value;
    return this;
  }

  text_bg(value: ColorInput): this {
    this._style["text_bg"] = value;
    return this;
  }

  font_family(value: string): this {
    this._style["font_family"] = value;
    return this;
  }

  font_weight(value: FontWeightName): this {
    this._style["font_weight"] = value;
    return this;
  }
}
