[package]
name = "steward-plugin-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
steward-ipc-protocol = { path = "../crates/ipc-protocol" }
steward-plugin-registry = { path = "../crates/plugin-registry" }
rquickjs.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
regex.workspace = true
arboard.workspace = true
dirs.workspace = true
crossbeam-channel.workspace = true

[dev-dependencies]
