#!/usr/bin/env node
// Generate `src/styles.generated.ts` from the canonical UI spec.
//
// The style vocabulary and the theme color tokens live in the Rust crate
// (`crates/ui-components/src/virtual_tree/{style_table,color_tokens}.json`) and
// are the single source of truth: the host validator/materializer and this SDK
// both read them, so a method that type-checks in a plugin is a method the host
// accepts. CI regenerates this file and fails if the checked-in copy differs.
//
// Usage: node scripts/gen-styles.mjs [--check]

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const specDir = join(here, "..", "..", "..", "crates", "ui-components", "src", "virtual_tree");
const outFile = join(here, "..", "src", "styles.generated.ts");

const styleTable = JSON.parse(readFileSync(join(specDir, "style_table.json"), "utf8"));
const colorTokens = JSON.parse(readFileSync(join(specDir, "color_tokens.json"), "utf8"));

const argTypes = {
  length: "LengthInput",
  absolute: "AbsoluteInput",
  number: "number",
  color: "ColorInput",
  string: "string",
  weight: "FontWeightName",
};

const fontWeights = [
  "thin",
  "extra_light",
  "light",
  "normal",
  "medium",
  "semibold",
  "bold",
  "extra_bold",
  "black",
];

function union(values) {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

const methods = styleTable
  .map(({ name, arg }) => {
    if (arg === "none") {
      return `  ${name}(): this {\n    this._style["${name}"] = true;\n    return this;\n  }`;
    }
    const type = argTypes[arg];
    if (!type) {
      throw new Error(`unknown arg kind '${arg}' for style method '${name}'`);
    }
    return `  ${name}(value: ${type}): this {\n    this._style["${name}"] = value;\n    return this;\n  }`;
  })
  .join("\n\n");

const output = `// AUTO-GENERATED by scripts/gen-styles.mjs from
// crates/ui-components/src/virtual_tree/style_table.json and color_tokens.json.
// Do not edit by hand: run \`node scripts/gen-styles.mjs\`.

export type ThemeColorToken = ${union(colorTokens)};

export type ColorInput = ThemeColorToken | \`#\${string}\`;

export type LengthInput = number | \`\${number}px\` | \`\${number}%\`;

export type AbsoluteInput = number | \`\${number}px\`;

export type FontWeightName = ${union(fontWeights)};

/**
 * Base class of every element builder. Each method here is one entry of the
 * host's canonical style table, so the two cannot drift.
 */
export class StyledElement {
  protected _style: Record<string, unknown> = {};

  /** Escape hatch for a style method added to the table after an SDK release. */
  style(name: string, value: unknown): this {
    this._style[name] = value;
    return this;
  }

${methods}
}
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(outFile, "utf8");
  if (current !== output) {
    console.error("styles.generated.ts is out of date; run `node scripts/gen-styles.mjs`");
    process.exit(1);
  }
} else {
  writeFileSync(outFile, output);
}
