[package]
name = "steward-core-engine"
version.workspace = true
edition.workspace = true

[dependencies]
nucleo.workspace = true
pinyin.workspace = true
serde.workspace = true
anyhow.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61", features = [
    "Win32_UI_Shell",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
] }
widestring = "1"
